"""Antigravity binary wrapper injection and restoration."""

from __future__ import annotations

import os
import stat

from ag_warp.branding import APP_NAME
from ag_warp.discovery import AntigravityVersion, sha256_file
from ag_warp.shell import Shell
from ag_warp.ui import console

# The wrapper script uses relative paths so it survives version directory renames.
_WRAPPER_TEMPLATE = """\
#!/usr/bin/env sh
# {app_name} wrapper — generated by {app_name}, do not edit
set -eu

GROUP_NAME="{group_name}"
REAL="$(dirname "$0")/antigravity-server.real"
GID="$(getent group "$GROUP_NAME" | cut -d: -f3)"

exec setpriv --regid "$GID" --clear-groups "$REAL" "$@"
"""


def inject_wrapper(
    version: AntigravityVersion,
    group_name: str,
    shell: Shell,
) -> dict[str, str]:
    """Inject the GID wrapper into an unwrapped Antigravity binary.

    Returns a dict of metadata for state.json recording.
    """
    server = version.server_binary
    real = version.real_binary

    # 1. Record original binary checksum.
    original_sha = sha256_file(server)

    # 2. Move original to .real.
    console.print(f"  Moving {server.name} → {real.name} …")
    shell.run(["mv", str(server), str(real)])

    # 3. Write wrapper.
    wrapper_content = _WRAPPER_TEMPLATE.format(app_name=APP_NAME, group_name=group_name)
    console.print(f"  Writing wrapper {server.name} …")
    if not shell.dry_run:
        server.write_text(wrapper_content)
        server.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)

    # 4. Ensure .real is executable.
    if not shell.dry_run and real.exists():
        current = real.stat().st_mode
        real.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    wrapper_sha = sha256_file(server) if not shell.dry_run else "dry-run"

    return {
        "version": version.version,
        "binary": str(server),
        "real_binary": str(real),
        "original_sha256": original_sha,
        "wrapper_sha256": wrapper_sha,
    }


def safe_restore(
    version: AntigravityVersion,
    expected_wrapper_sha: str | None,
    shell: Shell,
) -> bool:
    """Safely restore the original binary from .real.

    Returns ``True`` if the restore was performed.

    Conditions for safe restore (ALL must hold):
    1. Current antigravity-server contains the ag-wrap wrapper marker.
    2. antigravity-server.real exists.
    3. If we have an expected checksum, it must match the current wrapper.
    4. .real is executable.
    """
    server = version.server_binary
    real = version.real_binary

    # Check 1: Is current server our wrapper?
    if version.wrapper_status not in ("wrapped", "stale"):
        console.print(
            f"  [yellow]⚠ {server.name} is not an {APP_NAME} wrapper. Skipping restore.[/yellow]"
        )
        return False

    # Check 2: Does .real exist?
    if not real.exists():
        console.print(f"  [yellow]⚠ {real.name} not found. Skipping restore.[/yellow]")
        return False

    # Check 3: Checksum match.
    if expected_wrapper_sha:
        actual_sha = sha256_file(server)
        if actual_sha != expected_wrapper_sha:
            console.print(
                f"  [yellow]⚠ Wrapper checksum mismatch. Skipping restore.[/yellow]\n"
                f"    Expected: {expected_wrapper_sha[:16]}…\n"
                f"    Actual:   {actual_sha[:16]}…"
            )
            return False

    # Check 4: Is .real executable?
    if not os.access(real, os.X_OK):
        console.print(f"  [yellow]⚠ {real.name} is not executable. Skipping restore.[/yellow]")
        return False

    # All checks passed — restore.
    console.print(f"  Restoring {real.name} → {server.name} …")
    shell.run(["rm", "-f", str(server)])
    shell.run(["mv", str(real), str(server)])

    if not shell.dry_run:
        server.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)

    return True
